const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = vm.createContext({});
vm.runInContext(fs.readFileSync('resources/views/components/chat-message-state.blade.php', 'utf8').replace(/@json\(route\('chat.session'\)\)/g, '"/chat/session"'), context);
const merge = context.mergeChatMessages;
const ids = rows => Array.from(rows, row => row.id);
const previous = {id:1, content:'Khách hỏi'};
const pending = {id:'temp_1', content:'Admin trả lời'};
let state = merge([previous, pending], [previous]);
assert.deepEqual(ids(state), [1, 'temp_1'], 'Polling before POST completes must retain pending reply');
const saved = {id:2, content:'Admin trả lời'};
state = merge(state.filter(row => row.id !== pending.id), [saved]);
state = merge(state, [previous]);
assert.deepEqual(ids(state), [1,2], 'A stale response cannot remove an acknowledged reply');
state = merge(state, [previous, saved]);
assert.deepEqual(ids(state), [1,2], 'Repeated snapshots cannot duplicate replies');
state = merge(state, []);
assert.deepEqual(ids(state), [1,2], 'Empty older snapshots cannot erase the conversation');
assert.deepEqual(ids(merge([], [{id:5}, {id:3}])), [3,5]);
console.log('PASS: pending and saved replies survive delayed/empty polling without duplication.');
(async () => {
    const requests = [];
    context.fetch = async (url, options) => {
        requests.push({url, options});
        return url === '/chat/session' ? {ok:true, json:async()=>({user_id:7, csrf_token:'fresh-token'})} : {ok:true, status:200, json:async()=>({id:3})};
    };
    const saved = await context.sendStaffChat('/admin/chat/send', {message:'Reply',user_id:8}, 7);
    assert.equal(saved.id, 3);
    assert.equal(requests[1].options.headers['X-CSRF-TOKEN'], 'fresh-token');
    assert.equal(JSON.parse(requests[1].options.body).expected_user_id, 7);
    requests.length = 0;
    await assert.rejects(context.sendStaffChat('/admin/chat/send', {message:'Reply'}, 99), /đổi tài khoản/);
    assert.equal(requests.length, 1, 'Never POST as a different logged-in account');
    context.fetch = async url => url === '/chat/session' ? {ok:true,json:async()=>({user_id:7,csrf_token:'fresh'})} : {ok:false,status:500,json:async()=>{throw new Error('HTML error page');}};
    await assert.rejects(context.sendStaffChat('/admin/chat/send', {message:'Reply'}, 7), /HTTP 500/);
    console.log('PASS: fresh CSRF, changed-account guard and server failures are handled.');
})().catch(error => { console.error(error); process.exitCode=1; });
