const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const context = vm.createContext({});
vm.runInContext(fs.readFileSync('resources/views/components/chat-message-state.blade.php', 'utf8'), context);
const merge = context.mergeChatMessages;
const ids = rows => Array.from(rows, row => row.id);
const previous = {id:1, content:'Khách hỏi'};
const pending = {id:'temp_1', content:'Admin trả lời'};
let state = merge([previous, pending], [previous]);
assert.deepEqual(ids(state), [1, 'temp_1'], 'Polling before POST completes must retain pending reply');
const saved = {id:2, content:'Admin trả lời'};
state = merge(state.filter(row => row.id !== pending.id), [saved]);
state = merge(state, [previous]);
assert.deepEqual(ids(state), [1,2], 'A stale response cannot remove an acknowledged reply');
state = merge(state, [previous, saved]);
assert.deepEqual(ids(state), [1,2], 'Repeated snapshots cannot duplicate replies');
state = merge(state, []);
assert.deepEqual(ids(state), [1,2], 'Empty older snapshots cannot erase the conversation');
assert.deepEqual(ids(merge([], [{id:5}, {id:3}])), [3,5]);
console.log('PASS: pending and saved replies survive delayed/empty polling without duplication.');
